In syscalls.py now
firstcall called with 5 arguments
The time is now Fri Mar  4 08:13:17 2011
firstcall exited with status 1
