In syscalls.py now
firstcall called with 5 arguments
The time is now Wed Apr 11 13:55:00 2007
firstcall exited with status 1
firstcall called with 5 arguments
The time is now Wed Apr 11 13:58:00 2007
The process ID is fake
