<-PYT:import fakeurllib
<-PYT:fakeurllib.urlopen('foo://no.such.site')
->RET:raise Instance('URLError(IOError)', 'urlerror1')
<-PYT:urlerror1.args
->RET:('No such site, you wally!',)
<-PYT:fakeurllib.urlopen('foo://another.no.such.site')
->RET:raise Instance('URLError', 'urlerror2')
<-PYT:urlerror2.__str__()
->RET:"<urlopen error (-2, 'Now you're really getting on my nerves!')>"
